name: Build

on:
  push:
    branches: 
      - master


jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v1
      - uses: action/setup-node@v1
      with:
        node-version: 18.x
    
      - name: Build
        run: cd client && npm install && npm run build

      - name: Publish
        uses: nwtgck/actions-netlify@v2.0
        with:
           publish-dir: './build'
           production-deploy: true
           github-token: ${{ secrets.GITHUB_TOKEN }}
           deploy-message: "Deploy from GitHub Actions"
           enable-pull-request-comment: false
           enable-commit-comment: false
           overwrites-pull-request-comment: true
         env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}